/**
 * Questions for «¿Cuánto me conocés?». Written as a headline so they read the
 * same for both: «Sobre vos: …» to the one answering, «Sobre Ceci: …» to the
 * one guessing. Light and silly on purpose.
 */
export const KNOW_ME_QUESTIONS: { q: string; options: [string, string, string, string] }[] = [
  { q: 'El postre que elegiría', options: ['Helado', 'Flan con dulce de leche', 'Chocotorta', 'Fruta, en serio'] },
  { q: 'El superpoder que elegiría', options: ['Volar', 'Teletransportarse', 'Leer mentes', 'Pausar el tiempo'] },
  { q: 'Su domingo ideal', options: ['Dormir hasta el mediodía', 'Asado con gente', 'Maratón de series', 'Salir a pasear'] },
  { q: 'Lo primero que hace al despertarse', options: ['Mirar el celular', 'Café o mate', 'Remolonear', 'Ir al baño corriendo'] },
  { q: 'Si ganara la lotería, primero', options: ['Viajaría', 'Se compraría una casa', 'Lo ahorraría todo', 'Renunciaría al trabajo'] },
  { q: 'El animal que sería', options: ['Gato', 'Perro', 'Perezoso', 'Delfín'] },
  { q: 'Su comida de bajón', options: ['Pizza', 'Empanadas', 'Papas fritas', 'Helado del pote'] },
  { q: 'En una fiesta, se lo encuentra', options: ['Bailando', 'En la cocina', 'Charlando en un rincón', 'Yéndose temprano'] },
  { q: 'Su manera de viajar favorita', options: ['Avión', 'Ruta en auto', 'Tren', 'Barco'] },
  { q: 'El lugar donde viviría', options: ['Playa', 'Montaña', 'Gran ciudad', 'Campo'] },
  { q: 'Lo que más le molesta', options: ['Que mastiquen fuerte', 'La impuntualidad', 'Los mensajes de voz largos', 'Que le toquen la comida'] },
  { q: 'Su estación del año', options: ['Verano', 'Otoño', 'Invierno', 'Primavera'] },
  { q: 'Si fuera un personaje de cuento', options: ['El héroe', 'El villano simpático', 'El sabio', 'El bufón'] },
  { q: 'Cómo duerme', options: ['Boca abajo', 'De costado', 'Boca arriba', 'Como un pulpo, ocupando todo'] },
  { q: 'Su relación con el despertador', options: ['Se levanta al primer sonido', 'Posterga 3 veces', 'Posterga 10 veces', 'No usa, se despierta solo'] },
  { q: 'El género de música que pone en el auto', options: ['Rock nacional', 'Cumbia', 'Pop', 'Podcast, no música'] },
  { q: 'Lo que pediría en un bar', options: ['Cerveza', 'Fernet', 'Vino', 'Una gaseosa'] },
  { q: 'Su talento oculto', options: ['Cocinar', 'Imitar voces', 'Dibujar', 'Encontrar cosas perdidas'] },
  { q: 'En un apocalipsis zombi sería', options: ['El líder', 'El que cocina', 'El primero en caer', 'El que se esconde y sobrevive'] },
  { q: 'Su snack de película', options: ['Pochoclo', 'Chocolate', 'Papitas', 'Nada, mira concentrado'] },
  { q: 'Cómo reacciona a una película de terror', options: ['Se tapa los ojos', 'Se ríe', 'Se duerme', 'Grita'] },
  { q: 'El cumpleaños soñado', options: ['Fiesta enorme', 'Cena tranquila', 'Viaje sorpresa', 'Que nadie se acuerde'] },
  { q: 'Su orden en la casa', options: ['Todo impecable', 'Caos organizado', 'La silla con ropa', 'Mejor no preguntar'] },
  { q: 'El deporte que haría', options: ['Fútbol', 'Natación', 'Yoga', 'Ninguno, gracias'] },
  { q: 'Con qué personaje histórico cenaría', options: ['Cleopatra', 'Einstein', 'San Martín', 'Frida Kahlo'] },
  { q: 'Si tuviera un día libre sorpresa', options: ['Dormir', 'Salir de compras', 'Ordenar la casa', 'Llamar a amigos'] },
  { q: 'El emoji que más usa', options: ['😂', '❤️', '🙃', '👍'] },
  { q: 'Su pedido de pizza', options: ['Muzza', 'Napolitana', 'Fugazzeta', 'Con ananá, sin culpa'] },
  { q: 'Cómo festeja un gol', options: ['Grita como loco', 'Aplaude tranquilo', 'Ni se entera', 'Llora'] },
  { q: 'Si fuera un color', options: ['Azul', 'Rojo', 'Verde', 'Negro'] },
  { q: 'Lo que llevaría a una isla desierta', options: ['Un libro', 'Un cuchillo', 'Música', 'A su pareja, obvio'] },
  { q: 'Su mayor miedo ridículo', options: ['Las arañas', 'Las palomas', 'Los payasos', 'Quedarse sin batería'] },
  { q: 'Cómo maneja', options: ['Tranquilo', 'Como en una carrera', 'Puteando a todos', 'Prefiere que maneje otro'] },
  { q: 'Su plan de viernes a la noche', options: ['Salir', 'Pedir comida y peli', 'Dormir temprano', 'Juntada en casa'] },
  { q: 'Lo que hace cuando está nervioso', options: ['Come', 'Habla sin parar', 'Se queda callado', 'Limpia'] },
  { q: 'El trabajo de sus sueños', options: ['Chef', 'Astronauta', 'Músico', 'Millonario sin trabajar'] },
  { q: 'Su relación con las plantas', options: ['Las cuida como hijas', 'Se le mueren todas', 'Solo de plástico', 'Tiene una sola, sobreviviente'] },
  { q: 'En el supermercado', options: ['Va con lista', 'Compra lo que ve', 'Siempre se olvida algo', 'Pide por app'] },
  { q: 'El desayuno perfecto', options: ['Medialunas', 'Tostadas con palta', 'Yogur con frutas', 'Solo café'] },
  { q: 'Si fuera un mueble', options: ['Un sillón cómodo', 'Una biblioteca', 'Una cama', 'Una heladera'] },
  { q: 'Cómo pide perdón', options: ['Con palabras', 'Con comida', 'Con un abrazo', 'Haciéndose el distraído'] },
  { q: 'Su reacción a un spoiler', options: ['Furia total', 'No le importa', 'Lo busca a propósito', 'Llora en silencio'] },
  { q: 'Lo primero que mira de una casa', options: ['La cocina', 'La luz', 'El baño', 'Si entran plantas'] },
  { q: 'El juego de mesa favorito', options: ['Truco', 'Uno', 'Monopoly', 'Ajedrez'] },
  { q: 'Cómo está su celular', options: ['Batería siempre al 100', 'Siempre al 3 %', 'Mil apps abiertas', 'Pantalla rota'] },
  { q: 'Su olor favorito', options: ['Pan recién hecho', 'Lluvia', 'Café', 'Ropa limpia'] },
  { q: 'Si fuera un dulce', options: ['Alfajor', 'Chupetín', 'Caramelo de miel', 'Bombón'] },
  { q: 'En un viaje, siempre', options: ['Lleva de más', 'Se olvida algo', 'Planifica todo', 'Improvisa'] },
  { q: 'Su forma de cantar', options: ['En la ducha', 'En el auto a los gritos', 'Nunca', 'Bajito, sin que lo escuchen'] },
  { q: 'La mascota que tendría', options: ['Un perro grande', 'Un gato', 'Un loro', 'Un pez, poca responsabilidad'] },
  { q: 'Qué haría con una máquina del tiempo', options: ['Ir al futuro', 'Ver dinosaurios', 'Cambiar algo del pasado', 'Volver a un momento lindo'] },
  { q: 'Cómo come las papas fritas', options: ['Con kétchup', 'Con mayonesa', 'Solas', 'Con todo junto'] },
  { q: 'Su frase de cabecera', options: ['«Ya fue»', '«Cinco minutos más»', '«¿Qué comemos?»', '«Tranqui»'] },
  { q: 'Si fuera un clima', options: ['Sol radiante', 'Tormenta', 'Nublado tranquilo', 'Brisa de primavera'] },
  { q: 'El regalo que más le gusta recibir', options: ['Algo hecho a mano', 'Una experiencia', 'Comida rica', 'Plata, práctico'] },
  { q: 'Su lugar de la casa', options: ['El sillón', 'La cama', 'La cocina', 'El balcón'] },
  { q: 'Cuando hay una araña', options: ['La saca con cuidado', 'La mata', 'Grita', 'Le pone nombre'] },
  { q: 'El héroe de su infancia', options: ['Un superhéroe', 'Un dibujito', 'Un futbolista', 'Un familiar'] },
  { q: 'Cómo elige qué ver', options: ['Lo decide rápido', 'Media hora en el menú', 'Pide recomendaciones', 'Lo de siempre'] },
  { q: 'Su relación con la cocina', options: ['Chef de primera', 'Lo básico', 'Quema el agua', 'Solo microondas'] },
];
