import 'server-only';
import type { Tema } from '@/lib/temas';
import { minifyCss } from './minify';
import bullet from './bullet';
import menta from './menta';
import tinta from './tinta';
import pizarra from './pizarra';
import mostaza from './mostaza';
import cacao from './cacao';
import hadas from './hadas';
import pradera from './pradera';
import acuarela from './acuarela';
import dragon from './dragon';
import hongo from './hongo';
import mariposas from './mariposas';
import campanitas from './campanitas';
import cine from './cine';
import videoclub from './videoclub';
import marea from './marea';
import atardecer from './atardecer';
import frutilla from './frutilla';
import galaxia from './galaxia';
import pergamino from './pergamino';
import castillo from './castillo';
import vitral from './vitral';
import taberna from './taberna';
import heraldica from './heraldica';
import druidas from './druidas';
import alquimia from './alquimia';
import arcade from './arcade';
import bolsillo from './bolsillo';
import aventura from './aventura';
import mazmorra from './mazmorra';
import plataformas from './plataformas';
import bloques from './bloques';
import ciudad from './ciudad';
import reinopixel from './reinopixel';
import fuego from './fuego';
import hielo from './hielo';
import wyvern from './wyvern';
import tesoro from './tesoro';
import mapa from './mapa';
import torneo from './torneo';
import grimorio from './grimorio';
import forja from './forja';
import invasion from './invasion';
import clasificado from './clasificado';
import marte from './marte';
import nebulosa from './nebulosa';
import abduccion from './abduccion';
import orbital from './orbital';
import sakura from './sakura';
import shonen from './shonen';
import manga from './manga';
import magica from './magica';
import mecha from './mecha';
import neotokio from './neotokio';
import espiritus from './espiritus';
import samurai from './samurai';
import vaporwave from './vaporwave';
import terminal from './terminal';
import dinos from './dinos';
import piratas from './piratas';
import comic from './comic';
import brujas from './brujas';
import oeste from './oeste';

/**
 * Each theme's CSS, as text. It stays on the server: the layout inlines only
 * the active theme into the HTML, and `/theme-css/<id>.css` serves the others
 * so Ajustes can preview them. The CSS a phone downloads does not grow with
 * every new theme.
 *
 * «papel» is not here: it lives in `styles/temas.css` as the fallback.
 *
 * Illustrated textures live in `public/textures/` with a content hash in the
 * name so they can be cached forever. The fairy ones come from
 * `scripts/arte-hadas.py`, the newer groups from `scripts/theme-art.ts`
 * (`npm run themes:art`): edit there and regenerate.
 *
 * Generated by `npm run themes:index` from `TEMAS`. Do not edit by hand.
 */
const SOURCES: Partial<Record<Tema, string>> = {
  bullet,
  menta,
  tinta,
  pizarra,
  mostaza,
  cacao,
  hadas,
  pradera,
  acuarela,
  dragon,
  hongo,
  mariposas,
  campanitas,
  cine,
  videoclub,
  marea,
  atardecer,
  frutilla,
  galaxia,
  pergamino,
  castillo,
  vitral,
  taberna,
  heraldica,
  druidas,
  alquimia,
  arcade,
  bolsillo,
  aventura,
  mazmorra,
  plataformas,
  bloques,
  ciudad,
  reinopixel,
  fuego,
  hielo,
  wyvern,
  tesoro,
  mapa,
  torneo,
  grimorio,
  forja,
  invasion,
  clasificado,
  marte,
  nebulosa,
  abduccion,
  orbital,
  sakura,
  shonen,
  manga,
  magica,
  mecha,
  neotokio,
  espiritus,
  samurai,
  vaporwave,
  terminal,
  dinos,
  piratas,
  comic,
  brujas,
  oeste,
};

const ready = new Map<Tema, string>();

/** The theme's CSS, minified. Empty for «papel» and for a theme without a file. */
export function themeCss(theme: Tema): string {
  let css = ready.get(theme);
  if (css === undefined) {
    css = minifyCss(SOURCES[theme] ?? '');
    ready.set(theme, css);
  }
  return css;
}
