import { SWATCHES } from './theme-swatches';

/**
 * The themes: the id (stored in `perfiles.tema` and written to `data-tema`),
 * the name shown in Ajustes and the group it is listed under.
 *
 * Each theme's CSS lives in `styles/themes/<id>.ts` («papel» in
 * `styles/temas.css`). The swatch and browser bar hex come from there:
 * `npm run themes:index` writes them to `lib/theme-swatches.ts`.
 *
 * To add a theme: list it here, write its CSS, then `npm run themes:index`,
 * `npm run themes:test` and `npm run db:generate` (the database check is
 * built from this list).
 */
export const TEMAS = [
  'papel',
  'bullet',
  'menta',
  'tinta',
  'pizarra',
  'mostaza',
  'cacao',
  'hadas',
  'pradera',
  'acuarela',
  'dragon',
  'hongo',
  'mariposas',
  'campanitas',
  'cine',
  'videoclub',
  'marea',
  'atardecer',
  'frutilla',
  'galaxia',
  'pergamino',
  'castillo',
  'vitral',
  'taberna',
  'heraldica',
  'druidas',
  'alquimia',
  'arcade',
  'bolsillo',
  'aventura',
  'mazmorra',
  'plataformas',
  'bloques',
  'ciudad',
  'reinopixel',
  'fuego',
  'hielo',
  'wyvern',
  'tesoro',
  'mapa',
  'torneo',
  'grimorio',
  'forja',
  'invasion',
  'clasificado',
  'marte',
  'nebulosa',
  'abduccion',
  'orbital',
  'sakura',
  'shonen',
  'manga',
  'magica',
  'mecha',
  'neotokio',
  'espiritus',
  'samurai',
  'vaporwave',
  'terminal',
  'dinos',
  'piratas',
  'comic',
  'brujas',
  'oeste',
] as const;
export type Tema = (typeof TEMAS)[number];
export type Modo = 'claro' | 'oscuro';

/** Groups for the swatches in Ajustes: sixty in a row is too many to choose from. */
export const GRUPOS = [
  { id: 'cuadernos', nombre: 'Cuadernos' },
  { id: 'hadas', nombre: 'De hadas' },
  { id: 'salidas', nombre: 'Salidas' },
  { id: 'medieval', nombre: 'Medievales' },
  { id: 'pixel', nombre: 'Pixel art' },
  { id: 'dragones', nombre: 'Dragones y reinos' },
  { id: 'espacio', nombre: 'Aliens y espacio' },
  { id: 'anime', nombre: 'Anime' },
  { id: 'sorpresas', nombre: 'Sorpresas' },
] as const;
export type Grupo = (typeof GRUPOS)[number]['id'];

const NAMES: Record<Tema, { nombre: string; grupo: Grupo }> = {
  papel: { nombre: 'Papel y washi', grupo: 'cuadernos' },
  bullet: { nombre: 'Bullet journal', grupo: 'cuadernos' },
  menta: { nombre: 'Menta granizada', grupo: 'cuadernos' },
  tinta: { nombre: 'Tinta china', grupo: 'cuadernos' },
  pizarra: { nombre: 'Pizarra', grupo: 'cuadernos' },
  mostaza: { nombre: 'Mostaza y oliva', grupo: 'cuadernos' },
  cacao: { nombre: 'Chocolate caliente', grupo: 'cuadernos' },
  hadas: { nombre: 'Jardín de hadas', grupo: 'hadas' },
  pradera: { nombre: 'Pradera de luz', grupo: 'hadas' },
  acuarela: { nombre: 'Acuarela y estrellas', grupo: 'hadas' },
  dragon: { nombre: 'Guarida del dragón', grupo: 'hadas' },
  hongo: { nombre: 'Hada del hongo', grupo: 'hadas' },
  mariposas: { nombre: 'Vuelo de mariposas', grupo: 'hadas' },
  campanitas: { nombre: 'Campanitas', grupo: 'hadas' },
  cine: { nombre: 'Sala de cine', grupo: 'salidas' },
  videoclub: { nombre: 'Videoclub', grupo: 'salidas' },
  marea: { nombre: 'Marea', grupo: 'salidas' },
  atardecer: { nombre: 'Atardecer', grupo: 'salidas' },
  frutilla: { nombre: 'Frutilla y crema', grupo: 'salidas' },
  galaxia: { nombre: 'Galaxia', grupo: 'salidas' },
  pergamino: { nombre: 'Pergamino', grupo: 'medieval' },
  castillo: { nombre: 'Castillo', grupo: 'medieval' },
  vitral: { nombre: 'Vitral', grupo: 'medieval' },
  taberna: { nombre: 'Taberna', grupo: 'medieval' },
  heraldica: { nombre: 'Heráldica', grupo: 'medieval' },
  druidas: { nombre: 'Bosque de druidas', grupo: 'medieval' },
  alquimia: { nombre: 'Alquimia', grupo: 'medieval' },
  arcade: { nombre: 'Arcade', grupo: 'pixel' },
  bolsillo: { nombre: 'Bolsillo verde', grupo: 'pixel' },
  aventura: { nombre: 'Aventura 16 bits', grupo: 'pixel' },
  mazmorra: { nombre: 'Mazmorra', grupo: 'pixel' },
  plataformas: { nombre: 'Plataformas', grupo: 'pixel' },
  bloques: { nombre: 'Mundo de bloques', grupo: 'pixel' },
  ciudad: { nombre: 'Ciudad 8 bits', grupo: 'pixel' },
  reinopixel: { nombre: 'Reino pixel', grupo: 'pixel' },
  fuego: { nombre: 'Dragón de fuego', grupo: 'dragones' },
  hielo: { nombre: 'Dragón de hielo', grupo: 'dragones' },
  wyvern: { nombre: 'Wyvern esmeralda', grupo: 'dragones' },
  tesoro: { nombre: 'Tesoro del dragón', grupo: 'dragones' },
  mapa: { nombre: 'Mapa del reino', grupo: 'dragones' },
  torneo: { nombre: 'Torneo', grupo: 'dragones' },
  grimorio: { nombre: 'Grimorio', grupo: 'dragones' },
  forja: { nombre: 'Forja enana', grupo: 'dragones' },
  invasion: { nombre: 'Invasión', grupo: 'espacio' },
  clasificado: { nombre: 'Archivo clasificado', grupo: 'espacio' },
  marte: { nombre: 'Planeta rojo', grupo: 'espacio' },
  nebulosa: { nombre: 'Nebulosa', grupo: 'espacio' },
  abduccion: { nombre: 'Abducción', grupo: 'espacio' },
  orbital: { nombre: 'Estación orbital', grupo: 'espacio' },
  sakura: { nombre: 'Sakura', grupo: 'anime' },
  shonen: { nombre: 'Shōnen', grupo: 'anime' },
  manga: { nombre: 'Manga', grupo: 'anime' },
  magica: { nombre: 'Chica mágica', grupo: 'anime' },
  mecha: { nombre: 'Mecha', grupo: 'anime' },
  neotokio: { nombre: 'Neo Tokio', grupo: 'anime' },
  espiritus: { nombre: 'Espíritus del bosque', grupo: 'anime' },
  samurai: { nombre: 'Samurái', grupo: 'anime' },
  vaporwave: { nombre: 'Vaporwave', grupo: 'sorpresas' },
  terminal: { nombre: 'Terminal', grupo: 'sorpresas' },
  dinos: { nombre: 'Dinosaurios', grupo: 'sorpresas' },
  piratas: { nombre: 'Piratas', grupo: 'sorpresas' },
  comic: { nombre: 'Cómic', grupo: 'sorpresas' },
  brujas: { nombre: 'Noche de brujas', grupo: 'sorpresas' },
  oeste: { nombre: 'Lejano oeste', grupo: 'sorpresas' },
};

type Swatch = { fondo: string; acento: string; tinta: string };

export const PALETAS = Object.fromEntries(
  TEMAS.map((t) => [t, { ...NAMES[t], ...SWATCHES[t] }]),
) as Record<Tema, { nombre: string; grupo: Grupo; claro: Swatch; oscuro: Swatch }>;

export function temaValido(tema: string | null | undefined): Tema {
  return TEMAS.includes(tema as Tema) ? (tema as Tema) : 'papel';
}
