/**
 * Builds, from `TEMAS` and the files in `styles/themes/`:
 *
 * - `styles/themes/index.ts`, the registry the server uses;
 * - `lib/theme-swatches.ts`, three hex values per mode for each theme (the
 *   swatches in Ajustes and the browser bar color), taken from the CSS so
 *   there are not two places to keep in sync by hand.
 *
 *   npm run themes:index
 *
 * A theme in `TEMAS` without a file yet is left out of the registry and shows
 * as «papel», so themes can be added one at a time.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { TEMAS } from '../lib/temas';
import { cssOf, hasThemeFile, resolve } from './theme-reading';

const ROOT = join(import.meta.dirname, '..');
const withFile = TEMAS.filter((t) => t !== 'papel' && hasThemeFile(t));

writeFileSync(
  join(ROOT, 'styles/themes/index.ts'),
  `import 'server-only';
import type { Tema } from '@/lib/temas';
import { minifyCss } from './minify';
${withFile.map((t) => `import ${t} from './${t}';`).join('\n')}

/**
 * Each theme's CSS, as text. It stays on the server: the layout inlines only
 * the active theme into the HTML, and \`/theme-css/<id>.css\` serves the others
 * so Ajustes can preview them. The CSS a phone downloads does not grow with
 * every new theme.
 *
 * «papel» is not here: it lives in \`styles/temas.css\` as the fallback.
 *
 * Illustrated textures live in \`public/textures/\` with a content hash in the
 * name so they can be cached forever. The fairy ones come from
 * \`scripts/arte-hadas.py\`, the newer groups from \`scripts/theme-art.ts\`
 * (\`npm run themes:art\`): edit there and regenerate.
 *
 * Generated by \`npm run themes:index\` from \`TEMAS\`. Do not edit by hand.
 */
const SOURCES: Partial<Record<Tema, string>> = {
${withFile.map((t) => `  ${t},`).join('\n')}
};

const ready = new Map<Tema, string>();

/** The theme's CSS, minified. Empty for «papel» and for a theme without a file. */
export function themeCss(theme: Tema): string {
  let css = ready.get(theme);
  if (css === undefined) {
    css = minifyCss(SOURCES[theme] ?? '');
    ready.set(theme, css);
  }
  return css;
}
`,
);

const rows: string[] = [];
for (const theme of TEMAS) {
  const css = await cssOf(theme);
  const v = css === null ? resolve('papel', '') : resolve(theme, css);
  if (!v) throw new Error(`${theme}: missing its light or dark block`);
  const s = (x: Record<string, string>) =>
    `{ fondo: '${x['--fondo']}', acento: '${x['--acento']}', tinta: '${x['--tinta']}' }`;
  rows.push(`  ${theme}: { claro: ${s(v.light)}, oscuro: ${s(v.dark)} },`);
}
writeFileSync(
  join(ROOT, 'lib/theme-swatches.ts'),
  `// Generated by \`npm run themes:index\` from each theme's CSS. Do not edit by hand.
import type { Tema } from './temas';

type Swatch = { fondo: string; acento: string; tinta: string };

export const SWATCHES: Record<Tema, { claro: Swatch; oscuro: Swatch }> = {
${rows.join('\n')}
};
`,
);

const missing = TEMAS.filter((t) => !hasThemeFile(t));
console.log(`${withFile.length + 1} themes with CSS${missing.length ? `; no file yet: ${missing.join(', ')}` : ''}`);
