/**
 * Writes theme textures. Every module in `scripts/art/` except `shared.ts` is a
 * group and default-exports `{ name: svg }`.
 *
 *   npm run themes:art            # every group
 *   npm run themes:art -- pixel   # just one
 *
 * For each group:
 * - each SVG goes to `public/textures/<name>-<hash>.svg`. The content hash in
 *   the name lets the file be cached forever (see next.config.ts);
 * - `styles/themes/textures/<group>.ts` maps `T[name]` to `"url('...')"`,
 *   which is what theme CSS uses;
 * - SVGs the group no longer produces are deleted.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ART = join(import.meta.dirname, 'art');
const TEXTURES = join(import.meta.dirname, '..', 'public', 'textures');
const MANIFESTS = join(import.meta.dirname, '..', 'styles', 'themes', 'textures');

const requested = process.argv.slice(2);
const groups = readdirSync(ART)
  .filter((f) => f.endsWith('.ts') && f !== 'shared.ts')
  .map((f) => f.slice(0, -3))
  .filter((g) => requested.length === 0 || requested.includes(g));

for (const group of groups) {
  const drawings: Record<string, string> = (await import(join(ART, `${group}.ts`))).default;
  const manifest = join(MANIFESTS, `${group}.ts`);
  const before = existsSync(manifest)
    ? [...readFileSync(manifest, 'utf8').matchAll(/\/textures\/([\w-]+\.svg)/g)].map((m) => m[1]!)
    : [];

  const now: Record<string, string> = {};
  for (const [name, content] of Object.entries(drawings)) {
    if (!/^[a-z0-9]+(-[a-z0-9]+)+$/.test(name)) {
      throw new Error(`${group}: «${name}» must be theme-something in lowercase (at least one dash)`);
    }
    const clean = content.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
    const file = `${name}-${createHash('sha256').update(clean).digest('hex').slice(0, 10)}.svg`;
    writeFileSync(join(TEXTURES, file), clean);
    now[name] = file;
  }

  for (const old of before) {
    if (!Object.values(now).includes(old) && existsSync(join(TEXTURES, old))) unlinkSync(join(TEXTURES, old));
  }

  const rows = Object.entries(now)
    .map(([n, f]) => `  '${n}': "url('/textures/${f}')",`)
    .join('\n');
  writeFileSync(
    manifest,
    `// Generated by \`npm run themes:art -- ${group}\` from scripts/art/${group}.ts. Do not edit by hand.\nexport const T = {\n${rows}\n} as const;\n`,
  );
  const bytes = Object.values(now).reduce((s, f) => s + readFileSync(join(TEXTURES, f)).length, 0);
  console.log(`${group}: ${Object.keys(now).length} textures, ${(bytes / 1024).toFixed(1)} KB`);
}
