/**
 * Builds `lib/games/words.ts`, the word list for the word game.
 *
 *   npm run words
 *
 * Run by hand and commit the result: the app never touches the network for this.
 *
 * Two sources, both open:
 *   - FrequencyWords (hermitdave), word frequency from Spanish subtitles. It
 *     gives the order: which words are actually used.
 *   - Words (lorenbrichter), the Letterpress dictionary in Spanish. It gives
 *     validity: what is a word and what is a proper noun or English leaking in.
 *
 * TARGETS are the words to guess: the most frequent ones that are in the
 * dictionary, minus the proper nouns and swear words that survive the cross.
 * VALID are all five-letter words in the dictionary: an attempt is accepted
 * if it is there, so a correct but uncommon word is not rejected.
 */
import { writeFile } from 'node:fs/promises';

const FREQUENCY =
  'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/es/es_50k.txt';
const DICTIONARY = 'https://raw.githubusercontent.com/lorenbrichter/Words/master/Words/es.txt';

const TARGET_COUNT = 800;

/** Below this many appearances a subtitle token is noise (typos, names), not a word. */
const MIN_FREQUENCY = 40;

/** Words people here actually use that neither list has: slang and food. */
const EXTRA = [
  'birra', 'bondi', 'morfi', 'sushi', 'ramen', 'tacos', 'pucho', 'chori', 'facha', 'posta',
  'laburo', 'guita', 'pibes', 'bardo', 'joda', 'mates', 'yerba', 'dulce', 'fiaca', 'chamu',
  'trucha', 'zafar', 'zafas', 'zafo', 'copado', 'groso', 'manso', 'mufas', 'mufa', 'afano',
].filter((w) => w.length === 5);

/** What the cross does not filter on its own: names, brands, swear words, English. */
const EXCLUDED = new Set([
  'james', 'henry', 'paris', 'maria', 'simon', 'julia', 'lucas', 'vegas', 'robin', 'bruce',
  'rusia', 'japon', 'china', 'india', 'grant', 'pedro', 'diana', 'cesar', 'diego', 'marte',
  'mason', 'green', 'colin', 'corea', 'carla', 'paula', 'allen', 'bruno', 'times', 'nazis',
  'siria', 'maura', 'margo', 'petra', 'olive', 'spray', 'chips', 'nobel', 'islam', 'santa',
  'joder', 'perra', 'zorra', 'tetas', 'putas', 'porno', 'polla', 'jodan', 'jodas', 'jodio',
  'cogio', 'coger', 'cojan', 'cojas', 'orina', 'orgia', 'judio', 'macho', 'bolas', 'culpo',
]);

/** Lowercase, no accents, keeping the ñ. `[a-zñ]{5}` is what goes on the board. */
function normalize(word: string) {
  return word
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-̂̄-ͯ]/g, '') // everything but the tilde of the ñ (U+0303)
    .normalize('NFC');
}

const fiveLetters = (w: string) => /^[a-zñ]{5}$/.test(w);

async function download(url: string) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url}: ${r.status}`);
  return r.text();
}

console.log('Downloading the lists…');
const [frequency, dictionary] = await Promise.all([download(FREQUENCY), download(DICTIONARY)]);

const valid = new Set<string>();
for (const line of dictionary.split('\n')) {
  const w = normalize(line);
  if (fiveLetters(w)) valid.add(w);
}

const targets: string[] = [];
const seen = new Set<string>();
for (const line of frequency.split('\n')) {
  const [token, count] = line.split(' ');
  const w = normalize(token ?? '');
  if (!fiveLetters(w) || seen.has(w)) continue;
  seen.add(w);
  // A frequent token is accepted as an attempt even if the dictionary lacks it
  // (voseo forms, slang): rejecting a word someone actually says is worse than
  // accepting a stray name.
  if (Number(count) >= MIN_FREQUENCY) valid.add(w);
  if (targets.length < TARGET_COUNT && valid.has(w) && !EXCLUDED.has(w)) targets.push(w);
}
for (const w of EXTRA) valid.add(normalize(w));

const sorted = [...valid].sort();

const output = `/**
 * Generated by \`npm run words\` (scripts/words.ts). Do not edit by hand.
 *
 * Sources: FrequencyWords (hermitdave, CC BY-SA 4.0) for the usage order and
 * Words (lorenbrichter, the Letterpress dictionary) for validity.
 *
 * TARGETS: ${targets.length} frequent words, the ones to guess.
 * VALID: ${sorted.length} five-letter words, the ones accepted as an attempt.
 * All lowercase and without accents, keeping the ñ.
 */

export const TARGETS: readonly string[] = ${JSON.stringify(targets)};

const ALL = \`${sorted.join('\n')}\`;

let index: Set<string> | null = null;

/** Whether it is accepted as an attempt. The index is built the first time it is asked. */
export function isValidWord(word: string) {
  index ??= new Set(ALL.split('\\n'));
  return index.has(word);
}
`;

await writeFile(new URL('../lib/games/words.ts', import.meta.url), output);
console.log(`Done: ${targets.length} targets, ${sorted.length} valid words.`);
